### ISSUE TITLE
Potentially incorrect check

### ISSUE THREAD

**Issue by nullbitx8** [Candy-Labs/CandyContracts#12]
Hey, cool project!

While reading through the code I saw a potentially incorrect check

https://github.com/Candy-Labs/CandyContracts/blob/main/contracts/CandyCreatorV1A.sol#L372

I imagine it should be checking for `require(_exists(...` rather than `require(!_exists(...`

Cheers

**Comment by kyokosdream** [comment]
You're right, thank you! I changed an ERC721A revert error to a require with a custom string and so this should be changed ASAP.

**Comment by kyokosdream** [comment]
Fixed in the latest commit. Thanks for your help. We just updated our contract to v3.0 of ERC721A and would have missed this without you.

**Comment by nullbitx8** [comment]
Np, glad to help! Great job on the project!
